-- =====================================================================
-- Cotizador Thin Laminates — 20 · Colores completos y CORRECTOS
-- Reinserta TODOS los colores con el mapeo ORIGINAL (tal como los pasó Dayanna):
--   México (region 'MXN')        = Lista A: Gris Metalizado, Alúmina, Walnut Heights, Skyline Walnut, Calcutta, White Marble...
--   Costa Rica/LATAM (region 'LATAM') = Lista B: Ámbar Wood, Nogal Grafito, Inox Satín, Gris...
-- Sirve para llenar el color de locker (locker_frente) que salía vacío. Correr UNA vez.
-- No afecta cotizaciones (la línea guarda el color por nombre).
-- =====================================================================
delete from public.color;

insert into public.color (nombre,grupo,ambito,region,tiempo_especial) values
  -- ===== MÉXICO (region 'MXN') = Lista A =====
  ('Negro','G1','cubierta_int','MXN',false),
  ('Gris Metalizado','G1','cubierta_int','MXN',false),
  ('Blanco','G1','cubierta_int','MXN',false),
  ('Alúmina','G1','cubierta_int','MXN',false),
  ('Grafito Nocturno','G1','cubierta_int','MXN',false),
  ('Walnut Heights','G1','cubierta_int','MXN',false),
  ('Skyline Walnut','G1','cubierta_int','MXN',false),
  ('Calcutta Marble','G2','cubierta_int','MXN',false),
  ('White Marble','G3','cubierta_int','MXN',false),
  ('Roble Lineal','G4','cubierta_ext','MXN',false),
  ('Italian Walnut','G4','cubierta_ext','MXN',false),
  ('Atenas','G4','cubierta_ext','MXN',false),
  ('Tiziano','G4','cubierta_ext','MXN',false),
  ('Industrial Concrete','G4','cubierta_ext','MXN',false),
  ('Dark Steel','G4','cubierta_ext','MXN',true),
  ('Vanilla','G4','cubierta_ext','MXN',true),
  ('Negro','G1','locker_frente','MXN',false),
  ('Gris Metalizado','G1','locker_frente','MXN',false),
  ('Blanco','G1','locker_frente','MXN',false),
  ('Alúmina','G1','locker_frente','MXN',false),
  ('Grafito Nocturno','G1','locker_frente','MXN',false),
  ('Walnut Heights','G1','locker_frente','MXN',false),
  ('Skyline Walnut','G1','locker_frente','MXN',false),
  ('Alúmina','INT','locker_interior','MXN',false),
  ('Negro','INT','locker_interior','MXN',false),
  ('Blanco','INT','locker_interior','MXN',false),
  ('Negro','G1','banca','MXN',false),
  ('Gris Metalizado','G1','banca','MXN',false),
  ('Blanco','G1','banca','MXN',false),
  ('Alúmina','G1','banca','MXN',false),
  ('Grafito Nocturno','G1','banca','MXN',false),
  ('Walnut Heights','G1','banca','MXN',false),
  ('Skyline Walnut','G1','banca','MXN',false),
  -- ===== COSTA RICA / LATAM (region 'LATAM') = Lista B =====
  ('Blanco','G1','cubierta_int','LATAM',false),
  ('Gris','G1','cubierta_int','LATAM',false),
  ('Grafito Nocturno','G1','cubierta_int','LATAM',false),
  ('Negro','G1','cubierta_int','LATAM',false),
  ('Ámbar Wood','G1','cubierta_int','LATAM',false),
  ('Nogal Grafito','G1','cubierta_int','LATAM',false),
  ('Inox Satín','G1','cubierta_int','LATAM',false),
  ('Roble Lineal','G4','cubierta_ext','LATAM',false),
  ('Italian Walnut','G4','cubierta_ext','LATAM',false),
  ('Atenas','G4','cubierta_ext','LATAM',false),
  ('Tiziano','G4','cubierta_ext','LATAM',false),
  ('Industrial Concrete','G4','cubierta_ext','LATAM',false),
  ('Dark Steel','G4','cubierta_ext','LATAM',true),
  ('Vanilla','G4','cubierta_ext','LATAM',true),
  ('Negro','G1','locker_frente','LATAM',false),
  ('Gris Metalizado','G1','locker_frente','LATAM',false),
  ('Blanco','G1','locker_frente','LATAM',false),
  ('Alumina','G1','locker_frente','LATAM',false),
  ('Grafito Nocturno','G1','locker_frente','LATAM',false),
  ('Walnut Heights','G1','locker_frente','LATAM',false),
  ('Skyline Walnut','G1','locker_frente','LATAM',false),
  ('Alúmina','INT','locker_interior','LATAM',false),
  ('Blanco','G1','banca','LATAM',false),
  ('Gris','G1','banca','LATAM',false),
  ('Grafito Nocturno','G1','banca','LATAM',false),
  ('Negro','G1','banca','LATAM',false),
  ('Ámbar Wood','G1','banca','LATAM',false),
  ('Nogal Grafito','G1','banca','LATAM',false),
  ('Inox Satín','G1','banca','LATAM',false);
